# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chord.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"\x17\n\tIdMessage\x12\n\n\x02id\x18\x01 \x01(\x04\"\x17\n\tIpMessage\x12\n\n\x02ip\x18\x01 \x01(\t\"\x1b\n\rStatusMessage\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x0e\n\x0c\x45mptyMessage2\xc2\x02\n\x0c\x43hordService\x12\"\n\x08\x46indSucc\x12\n.IdMessage\x1a\n.IpMessage\x12\"\n\x08\x46indPred\x12\n.IdMessage\x1a\n.IpMessage\x12$\n\x07GetSucc\x12\r.EmptyMessage\x1a\n.IpMessage\x12$\n\x07GetPred\x12\r.EmptyMessage\x1a\n.IpMessage\x12\'\n\nUpdatePred\x12\n.IpMessage\x1a\r.EmptyMessage\x12\'\n\nUpdateSucc\x12\n.IpMessage\x1a\r.EmptyMessage\x12%\n\x08NotAlone\x12\n.IpMessage\x1a\r.EmptyMessage\x12%\n\x04Ping\x12\r.EmptyMessage\x1a\x0e.StatusMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDMESSAGE']._serialized_start=15
  _globals['_IDMESSAGE']._serialized_end=38
  _globals['_IPMESSAGE']._serialized_start=40
  _globals['_IPMESSAGE']._serialized_end=63
  _globals['_STATUSMESSAGE']._serialized_start=65
  _globals['_STATUSMESSAGE']._serialized_end=92
  _globals['_EMPTYMESSAGE']._serialized_start=94
  _globals['_EMPTYMESSAGE']._serialized_end=108
  _globals['_CHORDSERVICE']._serialized_start=111
  _globals['_CHORDSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
