# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chord.protos.chord_pb2 as chord__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chord_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindSuccessor = channel.unary_unary(
                '/ChordService/FindSuccessor',
                request_serializer=chord__pb2.IdMessage.SerializeToString,
                response_deserializer=chord__pb2.NodeMessage.FromString,
                _registered_method=True)
        self.FindPredecessor = channel.unary_unary(
                '/ChordService/FindPredecessor',
                request_serializer=chord__pb2.IdMessage.SerializeToString,
                response_deserializer=chord__pb2.NodeMessage.FromString,
                _registered_method=True)
        self.GetSuccessor = channel.unary_unary(
                '/ChordService/GetSuccessor',
                request_serializer=chord__pb2.EmptyMessage.SerializeToString,
                response_deserializer=chord__pb2.NodeMessage.FromString,
                _registered_method=True)
        self.GetPredecessor = channel.unary_unary(
                '/ChordService/GetPredecessor',
                request_serializer=chord__pb2.EmptyMessage.SerializeToString,
                response_deserializer=chord__pb2.NodeMessage.FromString,
                _registered_method=True)
        self.Notify = channel.unary_unary(
                '/ChordService/Notify',
                request_serializer=chord__pb2.NodeMessage.SerializeToString,
                response_deserializer=chord__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.ReverseNotify = channel.unary_unary(
                '/ChordService/ReverseNotify',
                request_serializer=chord__pb2.NodeMessage.SerializeToString,
                response_deserializer=chord__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.NotAloneNotify = channel.unary_unary(
                '/ChordService/NotAloneNotify',
                request_serializer=chord__pb2.NodeMessage.SerializeToString,
                response_deserializer=chord__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/ChordService/Ping',
                request_serializer=chord__pb2.EmptyMessage.SerializeToString,
                response_deserializer=chord__pb2.StatusResponseMessage.FromString,
                _registered_method=True)


class ChordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindSuccessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPredecessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSuccessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredecessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseNotify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotAloneNotify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindSuccessor': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSuccessor,
                    request_deserializer=chord__pb2.IdMessage.FromString,
                    response_serializer=chord__pb2.NodeMessage.SerializeToString,
            ),
            'FindPredecessor': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPredecessor,
                    request_deserializer=chord__pb2.IdMessage.FromString,
                    response_serializer=chord__pb2.NodeMessage.SerializeToString,
            ),
            'GetSuccessor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuccessor,
                    request_deserializer=chord__pb2.EmptyMessage.FromString,
                    response_serializer=chord__pb2.NodeMessage.SerializeToString,
            ),
            'GetPredecessor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredecessor,
                    request_deserializer=chord__pb2.EmptyMessage.FromString,
                    response_serializer=chord__pb2.NodeMessage.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=chord__pb2.NodeMessage.FromString,
                    response_serializer=chord__pb2.EmptyMessage.SerializeToString,
            ),
            'ReverseNotify': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseNotify,
                    request_deserializer=chord__pb2.NodeMessage.FromString,
                    response_serializer=chord__pb2.EmptyMessage.SerializeToString,
            ),
            'NotAloneNotify': grpc.unary_unary_rpc_method_handler(
                    servicer.NotAloneNotify,
                    request_deserializer=chord__pb2.NodeMessage.FromString,
                    response_serializer=chord__pb2.EmptyMessage.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=chord__pb2.EmptyMessage.FromString,
                    response_serializer=chord__pb2.StatusResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ChordService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindSuccessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/FindSuccessor',
            chord__pb2.IdMessage.SerializeToString,
            chord__pb2.NodeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPredecessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/FindPredecessor',
            chord__pb2.IdMessage.SerializeToString,
            chord__pb2.NodeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSuccessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/GetSuccessor',
            chord__pb2.EmptyMessage.SerializeToString,
            chord__pb2.NodeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredecessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/GetPredecessor',
            chord__pb2.EmptyMessage.SerializeToString,
            chord__pb2.NodeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/Notify',
            chord__pb2.NodeMessage.SerializeToString,
            chord__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReverseNotify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/ReverseNotify',
            chord__pb2.NodeMessage.SerializeToString,
            chord__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotAloneNotify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/NotAloneNotify',
            chord__pb2.NodeMessage.SerializeToString,
            chord__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChordService/Ping',
            chord__pb2.EmptyMessage.SerializeToString,
            chord__pb2.StatusResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
